name: Authentication Service
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install requirements
        run: pip install --no-cache-dir -r requirements.txt
      - name: run tests
        run: pytest --cov-report term-missing --cov=authentication
      - name: run lint
        run: pylint authentication tests
